global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['docker.for.mac.localhost:9090']
  - job_name: 'mlflow'
    static_configs:
      - targets: ['docker.for.mac.localhost:5000']
  - job_name: 'mlflow_1'
    static_configs:
      - targets: ['docker.for.mac.localhost:5001']
  - job_name: 'airflow'
    static_configs:
      - targets: ['docker.for.mac.localhost:8080']
